### ISSUE TITLE
gcs_list_buckets(proj) for a project with no existing buckets - better error handling?

### ISSUE THREAD

**Issue by j450h1** [cloudyr/googleCloudStorageR#100]
Came across this error after running this for a new GCP project with no buckets setup. I would expect it to return a message that there are currently no buckets created in this project.

``` r
library(googleCloudStorageR)
#> Setting scopes to https://www.googleapis.com/auth/devstorage.full_control
#> Successfully authenticated via {PATH_TO_MY_KEYFILE}
proj <- Sys.getenv("PROJECT_ID")
# currently no buckets in project
gcs_list_buckets(proj)
#> Error in as.POSIXct.default(t, format = "%Y-%m-%dT%H:%M:%S") : 
#>   do not know how to convert 't' to class "POSIXct"
#> Warning in lb(): API Data failed to parse.  Returning parsed from JSON content.
#>                     Use this to test against your data_parse_function.
#> NULL
```

<sup>Created on 2019-02-25 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by MarkEdmondson1234** [comment]
Thanks, should be fixed now!

**Comment by featherduino** [comment]
I am getting this error still with version : V googleCloudStorageR * 0.5.1

Error in as.POSIXct.default(t, format = "%Y-%m-%dT%H:%M:%S") : 
  do not know how to convert 't' to class “POSIXct”
Error: API Data failed to parse.  
             Wrote diagnostic object to 'gar_parse_error.rds', use googleAuthR::gar_debug_parsing('gar_parse_error.rds') to 
             debug the data_parse_function.

**Comment by MarkEdmondson1234** [comment]
Could you try this with the latest GitHub version?  Install first via `remotes::install_github("cloudyr/googleCloudStorageR")`

**Comment by featherduino** [comment]
yeah thanks for that but i install the repo using the same command yesterday that gave me the latest version. 

And on gar_debug_parsing - this is the error i get

 # When creating a GitHub issue, please include this output. ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
List of 3
 $ request       :List of 4
  ..$ req_url     : chr "https://www.googleapis.com/storage/v1/b/?project=funnel-social-data&prefix=&projection=noAcl"
  ..$ request_type: chr "GET"
  ..$ the_body    : NULL
  ..$ customConfig: NULL
 $ response      :List of 3
  ..$ data_parse_args: list()
  ..$ data_parse_func:function (x)  
  ..$ content        :List of 1
  .. ..$ kind: chr "storage#buckets"
 $ authentication:List of 1
  ..$ token:Classes 'TokenServiceAccount', 'Token2.0', 'Token', 'R6' Error in get(method, envir = home) : 
  lazy-load database '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/R6/R/R6.rdb' is corrupt
In addition: Warning message:
In get(method, envir = home) : internal error -3 in R_decompress1

**Comment by MarkEdmondson1234** [comment]
Thanks, that output is useful for debugging.  Its returning no content at all, so the auth method you are using has no buckets to list?  I'll move this to another issue because at the very least it should give a less confusing error message back.

**Comment by MarkEdmondson1234** [comment]
I found an issue with listing buckets, that should be fixed in the next commit - it was checking for a timestamp, rather than items in the returns API object, so even if you had buckets in your project it was saying they were not present.
